import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import AppLoader from "../components/AppLoader";
import { TransitionProvider } from "../components/TransistionLayer";
import PersistentNavbar from "../components/layout/PersistentNavbar";
import NavBar from "../components/layout/NavBar";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  // Change weight to "variable" instead of an array
  weight: "variable",
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html
      lang="en"
      className={`${inter.variable} ${playfairDisplay.variable} h-full antialiased`}
    >

<body className="min-h-full flex flex-col w-full overflow-x-hidden">
  <AppLoader>
    <TransitionProvider>
      <PersistentNavbar />
      {children}
    </TransitionProvider>
  </AppLoader>
</body>
    </html>
  );
}
